### ISSUE TITLE
Document convention of using `expedited` flag for when we force interruption of planned work

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#1529]
This was suggested by @gabrielamafra to help us get visibility on the frequency and characteristics of urgent requests that interrupt planned or in progress work.

The idea is that if any work is deemed so urgent that is MUST jump the queue, we should clearly flag this, so that we can see how often we end up needing to break concentration/focus and disrupt our plans. By making this visible, we'll be able to identify patterns that should help us reduce the frequency, thus giving us more time to focus and build up/maintain momentum, and greater assurance that we are spending our time working on the important stuff.

Let's

- [ ] Record this convention in our `COORDINATION.md` document
- [x] Start putting it in practice, beginning with labeling the current interrupting work (see https://github.com/informalsystems/apalache/labels/expedite)

**Comment by gabrielamafra** [comment]
Here are some perhaps useful references:

Section 'Types of Kanban Classes of Service for Risk Management' in [How to Manage Risk with Kanban Classes of Service?](https://kanbanize.com/kanban-resources/getting-started/kanban-classes-of-service) explains how expedites compare to other types of tasks

As for managing expedites in our project board, the most recommended approach is to use a swimlane (as explained [here](https://kanbanize.com/kanban-resources/kanban-software/kanban-swimlanes) - you can search for "expedite" to see this specific example), which is essentially a new line (rather then a new column). Since github doesn't support swimlanes, we can virtually just keep expedite cards at the top of the column to create a similar effect.

The guidelines on [How to Manage Unplanned Work in Kanban](https://getnave.com/blog/manage-unplanned-work-in-kanban/) can also be a nice read.

**Comment by shonfeder** [comment]
Super helpful. Thanks! 

I agree simulating a lane with the labels is probably a good solution for now. We can also use alternate views to filter these out. I created one here: https://github.com/orgs/informalsystems/projects/30/views/11
