### ISSUE TITLE
Add visibility of progress towards our strategic objectives into coordination practices

### ISSUE THREAD

**Issue by shonfeder** [apalache-mc/apalache#1892]
We don't currently seem to have great visibility into the progress we're making towards our main feature adds and objectives. We can (and do) use the milestones to record this, but we don't really have a process in place to surface and record significant achievements (or estimated progress towards those achievements).

One suggestion made by @tesnimab is that our quarterly retros should include some report on the "objective" progress made (in addition to the subjective reflection on our highlights and problems).

It would probably also be helpful to get some view on this on a weekly or monthly basis.

One practice I've seen work well is for a set of related smaller teams (about Apalache's size) to have *very short* weekly meetings where they report the major achievements or progress of each team in the previous week.

Other ideas?

@tesnimab noted the the need for this kind of feedback in conversation today.

**Comment by thpani** [comment]
Good points on improving our processes here.

I have a few questions for clarification:

> One suggestion made by @tesnimab is that our quarterly retros should include some report on the "objective" progress made (in addition to the subjective reflection on our highlights and problems).

By "report", do you mean a written document or oral discussion?
For the former, Igor did a report on Q1/2022 here: https://github.com/informalsystems/strategy/blob/main/projects/apalache/reports/report-2022-q1.md

For the latter, what I've seen in practice is similar to what we do for MondApalache, just with OKRs instead of Github issues, i.e., going over past quarter's OKRs for the retro, and next quarter's OKRs for planning. Now that we're using the Workflow explorer, we could do the same.
This kind of discussion presumes that there is enough information about next quarter's plans leading up to the retro.
It also enables people to write their own OKRs between retro and planning, i.e., both meetings are a sanity check / review for the team, instead of lengthy discussion.

> It would probably also be helpful to get some view on this on a weekly or monthly basis.
> 
> One practice I've seen work well is for a set of related smaller teams (about Apalache's size) to have _very short_ weekly meetings where they report the major achievements or progress of each team in the previous week.

Could you explain how this would differ from our MondApalache meeting?

**Comment by thpani** [comment]
cc @bugarela @Kukovec @rodrigo7491 @p-offtermatt

**Comment by konnov** [comment]
> We don't currently seem to have great visibility into the progress we're making towards our main feature adds and objectives. We can (and do) use the milestones to record this, but we don't really have a process in place to surface and record significant achievements (or estimated progress towards those achievements).

We could also introduce burndown charts for every milestone. Even better, if every issue is assigned a weight. A chart like this could be used for time estimates. So we don't have to argue about how close to completion we are. Obviously, the plot is not going to be monotonic. This is what makes time estimates hard.

**Comment by konnov** [comment]
For instance, look at the burndown chart for "variants and records". I don't know how to add issue weights to Github charts, if it's possible at all. But that looks to me like a good source of progress stats.

**Comment by thpani** [comment]
> We could also introduce burndown charts for every milestone. Even better, if every issue is assigned a weight. A chart like this could be used for time estimates. So we don't have to argue about how close to completion we are. Obviously, the plot is not going to be monotonic. This is what makes time estimates hard.

IMO burndown charts only make sense if the task is fully scoped, i.e., if the chart can't "burn up". Not so much the case with our work?

**Comment by konnov** [comment]
Sure. That's what I am saying. It can give you an estimate (if we guess initial weights for meta issues), but then it may easily burn up, effectively shifting the deadline. We just have to be aware of that. But it still can be useful for historic purposes, e.g., to illustrate that this is exactly what is happening.

**Comment by konnov** [comment]
higher-order management :)
